/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lv.brain.gradle;

import lv.brain.gradle.extension.JavaEnumFinderExtension;
import lv.brain.gradle.task.JavaEnumFinderTask;
import org.gradle.api.Plugin;
import org.gradle.api.Project;

/**
 * this class is used in /plugin/build.gradle as implementationClass
 */
@SuppressWarnings("unused")
public class JavaEnumFinderPlugin implements Plugin<Project> {
    @Override
    public void apply(Project project) {
        JavaEnumFinderExtension extension = project.getExtensions().create("javaEnumFinder", JavaEnumFinderExtension.class);

        JavaEnumFinderTask task = project.getTasks().create("javaEnumFind", JavaEnumFinderTask.class);

        project.afterEvaluate(proj -> {
            task.setTarget(extension.getTarget());
            task.setSources(extension.getSources());
            task.setFile(extension.getFile());
        });
    }
}
