/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lv.brain.gradle;

import lv.brain.gradle.extension.JavaEnumFinderExtension;
import lv.brain.gradle.task.JavaEnumFinderTask;
import org.gradle.api.Project;
import org.gradle.api.Plugin;

public class JavaEnumFinderPlugin implements Plugin<Project> {
    @Override
    public void apply(Project project) {
        JavaEnumFinderExtension extension = project.getExtensions().create("javaEnumFinder", JavaEnumFinderExtension.class);

        JavaEnumFinderTask task = project.getTasks().create("javaEnumFind", JavaEnumFinderTask.class);

        project.afterEvaluate(proj -> task.setTarget(extension.getTarget()));
    }
}
